#!/bin/bash

# Use jq to get raw data, then pipe through awk for all processing
jq -r '.name + " " + (.height|tostring) + " " + (.weight|tostring) + " " + .types[0].type.name' data.json | \
awk '{
    name = $1
    height = $2
    weight = $3
    type = $4
    
    # Capitalize first letter
    name = toupper(substr(name,1,1)) substr(name,2)
    type = toupper(substr(type,1,1)) substr(type,2)
    
    # Convert units
    formatted_height = height / 10
    formatted_weight = weight / 10
    
    printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", name, type, formatted_weight, formatted_height
}'
